project:
  name: fungi_segmentation

paths:
  images_dir: data/images
  masks_dir: data/masks
  runs_dir: runs
  outputs_dir: outputs

data:
  image_extensions: [".png", ".jpg", ".jpeg", ".tif", ".tiff"]
  patch_size: 256
  overlap: 128
  stride: 128
  filter_empty_patches: true
  mask_threshold: 127
  min_foreground_pixels: 128
  num_workers: 22
  persistent_workers: true
  prefetch_factor: 8
  pin_memory: true
  batch_size: 4
  image_size: null

augmentations:
  normalize: # do not touch this
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  train: # this can be edited
    horizontal_flip_p: 0.8
    vertical_flip_p: 0.5
    random_rotate_90_p: 0.8
    affine:
      translate_x: [-0.02, 0.02]
      translate_y: [-0.02, 0.02]
      scale: [0.90, 1.1]
      rotate: [-10, 10]
      p: 0.4
    random_brightness_contrast:
      brightness_limit: [-0.15, 0.15]
      contrast_limit: [-0.15, 0.15]
      p: 0.2
    random_gamma:
      gamma_limit: [90, 110]
      p: 0.2
    clahe:
      clip_limit: [1.0, 2.0]
      tile_grid_size: [8, 8]
      p: 0.1
    blur:
      gaussian_blur_limit: [3, 5]
      gaussian_sigma_limit: [0.2, 0.8]
      defocus_radius: [2, 3]
      defocus_alias_blur: [0.1, 0.3]
      p: 0.1
    gauss_noise_p: 0.05

cv:
  n_splits: 5
  shuffle_groups: true
  random_state: 42

split:
  mode: train_val # train_val or kfold
  val_source_ids: ['job_7_IN183 YNA 48h x500 1.tif','job_4_IN183 Agar 48h x500 3.tif','job_2_IN125 Agar 48h x500 2.tif','job_3_IN125 SNA 48h x500 3.tif','job_6_IN183 SNA 48h x500 4.tif']

model:
  name: unetplusplus_resnet34
  in_channels: 3
  num_classes: 1
  encoder_name: resnet34
  encoder_weights: imagenet
  decoder_normalization: instancenorm
  decoder_channels: [256, 128, 64, 32, 16]
  decoder_attention_type: scse # set to scse to enable SMP scSE attention in the decoder

loss:
  name: tversky_soft_cldice
  alpha: 0.3
  beta: 0.7
  tversky_weight: 0.7
  soft_cldice_weight: 0.3
  iterations: 3
  smooth: 1.0e-6
  cldice_smooth: 1.0

optimizer:
  name: adamw
  lr: 0.0001
  weight_decay: 0.0001

scheduler:
  name: reduce_on_plateau
  mode: max
  factor: 0.5
  patience: 4
  min_lr: 1.0e-6
  monitor: val_dice_per_patch



train:
  epochs: 150
  mixed_precision: true
  grad_clip: 1.0
  monitor: val_dice_per_patch
  monitor_mode: max
  threshold: 0.5
  enable_per_image_validation: true
  per_image_validation_interval: 10
  seed: 42
  device: auto
  use_tqdm: true

inference:
  threshold: 0.5
  save_probabilities: false
